version: "2"
services:
  db:
    image: postgres
    container_name: test_avito_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
  server:
    container_name: testapp
    depends_on:
      - db
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
